name: build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build jar
        run: ./build/build_one.sh 1.8 2.14.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          SOURCE_COMPAT: 1.8
          LOG4J_VERSION: 2.14.0
        with:
          file: build/Dockerfile8.app
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/example-app:8-latest
